/rsgs/scratch0/nasavare/comment_test/lab3/beat32.v
/rsgs/scratch0/nasavare/comment_test/lab3/shifter.v
/rsgs/scratch0/nasavare/comment_test/lab3/blinker.v
/rsgs/scratch0/nasavare/comment_test/lab3/programmable_blinker.v
/rsgs/scratch0/nasavare/comment_test/lab3/dff.v
/rsgs/scratch0/nasavare/comment_test/lab3/dffr.v
/rsgs/scratch0/nasavare/comment_test/lab3/dffre.v
/rsgs/scratch0/nasavare/comment_test/lab3/master_fsm.v
/rsgs/scratch0/nasavare/comment_test/lab3/lab3_top.v
/rsgs/scratch0/nasavare/comment_test/lab3/timer.v
/rsgs/scratch0/nasavare/comment_test/lab3/speed_shift.v
/rsgs/scratch0/nasavare/comment_test/lab3/bicycle_fsm.v
/rsgs/scratch0/nasavare/comment_test/lab3/mux_bs.v
/rsgs/scratch0/nasavare/comment_test/lab3/mux_ohs.v
